import { jsPDF } from 'jspdf';

/**
 * Report Generation Utility
 * Generates PDF, CSV, Excel, and JSON reports
 */

export function generatePDFReport(inspectionData) {
    const doc = new jsPDF();

    // Header Title
    doc.setFillColor(10, 18, 32);
    doc.rect(0, 0, 210, 35, 'F');

    doc.setTextColor(255, 222, 89);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('DVJ INDUSTRIAL AI PLATFORM', 14, 18);

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text('AUTOMATED QUALITY INSPECTION REPORT', 14, 27);

    // Metadata Block
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.text(`Inspection ID: ${inspectionData.inspectionId}`, 14, 45);
    doc.text(`Timestamp: ${new Date(inspectionData.timestamp).toLocaleString()}`, 14, 52);
    doc.text(`Component Type: ${inspectionData.partType}`, 14, 59);

    // Status Banner
    const isPass = inspectionData.status === 'PASS';
    doc.setFillColor(isPass ? 16 : 239, isPass ? 185 : 68, isPass ? 129 : 68);
    doc.rect(140, 42, 55, 20, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(inspectionData.status, 155, 55);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(14, 66, 196, 66);

    // Measurements Table
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text('1. DIMENSION & SHAPE ANALYSIS METRICS', 14, 76);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Outer Diameter: ${inspectionData.measurements?.outerDiameterMM || 120.0} mm`, 20, 86);
    doc.text(`Inner Bore ID: ${inspectionData.measurements?.innerBoreMM || 35.0} mm`, 20, 93);
    doc.text(`Circularity Index: ${inspectionData.measurements?.circularity || 0.98}`, 20, 100);
    doc.text(`Symmetry Factor: ${inspectionData.measurements?.symmetry || 0.99}`, 20, 107);
    doc.text(`Pipeline Processing Latency: ${inspectionData.latencyMs || 12.4} ms`, 20, 114);

    // Defect Classification Section
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('2. DEFECT CLASSIFICATION BREAKDOWN', 14, 128);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const defects = inspectionData.defects || [];
    if (defects.length === 0) {
        doc.text('No defects detected. Component satisfies 100% industrial tolerance thresholds.', 20, 138);
    } else {
        defects.forEach((d, idx) => {
            doc.setTextColor(220, 38, 38);
            doc.text(`• Defect ${idx + 1}: ${d} (Confidence: ${inspectionData.confidenceScore}%)`, 20, 138 + idx * 7);
        });
    }

    // 15 Stage Pipeline Summary
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('3. OPENCV 15-STAGE PIPELINE EXECUTED', 14, 165);

    const stages = [
        '1. Read Image', '2. Grayscale', '3. Gaussian Blur', '4. Threshold',
        '5. Morphology', '6. Edge Detection', '7. Contours', '8. Convex Hull',
        '9. Convexity Defects', '10. Bounding Box', '11. Dimension Measurement',
        '12. Shape Analysis', '13. Defect Detection', '14. Confidence Score', '15. PASS / FAIL'
    ];

    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    stages.forEach((s, idx) => {
        const col = idx < 8 ? 20 : 110;
        const row = 175 + (idx % 8) * 6;
        doc.text(`✓ ${s}`, col, row);
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by DVJ Group AI Expert Assistant | Industrial AI Platform', 14, 280);

    doc.save(`${inspectionData.inspectionId}_Report.pdf`);
}

export function generateCSVReport(records) {
    if (!records || !records.length) return;

    const headers = ['Inspection ID', 'Timestamp', 'Part Type', 'Status', 'Confidence Score (%)', 'Defects', 'Outer Diameter (mm)', 'Inner Bore (mm)', 'Latency (ms)'];
    const rows = records.map(r => [
        r.inspectionId,
        `"${r.timestamp}"`,
        r.partType,
        r.status,
        r.confidenceScore,
        `"${(r.defects || []).join('; ')}"`,
        r.measurements?.outerDiameterMM || 120.0,
        r.measurements?.innerBoreMM || 35.0,
        r.latencyMs || 14.2
    ]);

    const csvContent = [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
    downloadFile(csvContent, 'Industrial_Quality_Inspections.csv', 'text/csv;charset=utf-8;');
}

export function generateExcelReport(records) {
    if (!records || !records.length) return;

    // Excel XML Format
    let xml = '<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?>\n';
    xml += '<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n';
    xml += ' xmlns:o="urn:schemas-microsoft-com:office:office"\n';
    xml += ' xmlns:x="urn:schemas-microsoft-com:office:excel"\n';
    xml += ' xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">\n';
    xml += ' <Worksheet ss:Name="Inspections">\n  <Table>\n';

    // Header
    xml += '   <Row>\n';
    const headers = ['Inspection ID', 'Timestamp', 'Part Type', 'Status', 'Confidence Score', 'Defects', 'Outer Diameter (mm)', 'Latency (ms)'];
    headers.forEach(h => {
        xml += `    <Cell><Data ss:Type="String">${h}</Data></Cell>\n`;
    });
    xml += '   </Row>\n';

    // Rows
    records.forEach(r => {
        xml += '   <Row>\n';
        xml += `    <Cell><Data ss:Type="String">${r.inspectionId}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="String">${r.timestamp}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="String">${r.partType}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="String">${r.status}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="Number">${r.confidenceScore}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="String">${(r.defects || []).join('; ') || 'None'}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="Number">${r.measurements?.outerDiameterMM || 120.0}</Data></Cell>\n`;
        xml += `    <Cell><Data ss:Type="Number">${r.latencyMs || 14.2}</Data></Cell>\n`;
        xml += '   </Row>\n';
    });

    xml += '  </Table>\n </Worksheet>\n</Workbook>';

    downloadFile(xml, 'Industrial_Quality_Inspections.xls', 'application/vnd.ms-excel');
}

export function generateJSONReport(records) {
    const jsonStr = JSON.stringify(records, null, 2);
    downloadFile(jsonStr, 'Industrial_Quality_Inspections.json', 'application/json');
}

function downloadFile(content, fileName, mimeType) {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileName;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}
